# Generated by Django 3.1.5 on 2021-03-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnviromentalCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Condition', models.CharField(default=None, max_length=50, null=True, verbose_name='Условие')),
            ],
            options={
                'verbose_name': ('Условие эксплуатации',),
                'verbose_name_plural': 'Условия эксплуатации',
            },
        ),
        migrations.CreateModel(
            name='ModelTxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Название')),
                ('file', models.FileField(upload_to='upload_to/', verbose_name='Файл модели')),
            ],
            options={
                'verbose_name': ('Файл модели',),
                'verbose_name_plural': 'Файлы Моделей',
            },
        ),
        migrations.CreateModel(
            name='TechologyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Название')),
                ('file', models.FileField(upload_to='upload_to/', verbose_name='Файл технического описания')),
            ],
            options={
                'verbose_name': ('Техническое описание',),
                'verbose_name_plural': 'Технические описания',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': ('Тип',),
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='TransistorPOLEV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Название')),
                ('function', models.CharField(default=None, max_length=50, verbose_name='Производитель')),
                ('basicModel', models.CharField(default=None, max_length=50, verbose_name='Макс. мощность, Вт')),
                ('body', models.CharField(default=None, max_length=50, verbose_name='Корпус')),
                ('ready', models.BooleanField(default=True, verbose_name='Открытый доступ')),
                ('maxcurrent', models.CharField(max_length=255, verbose_name='Максимальный ток стока, А')),
                ('maxvoltageSI', models.CharField(max_length=255, verbose_name='Максимальное напряжение сток-истока, В')),
                ('maxvoltageZI', models.CharField(max_length=255, verbose_name='Максимальное напряжение затвор-исток, В')),
                ('conditions', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.enviromentalcondition', verbose_name='Условия эксплуатации')),
                ('down', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.modeltxt', verbose_name='Файл модели')),
                ('technicaldescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.techologytask', verbose_name='Файл технического описания')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.type', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransistorBP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Название')),
                ('function', models.CharField(default=None, max_length=50, verbose_name='Производитель')),
                ('basicModel', models.CharField(default=None, max_length=50, verbose_name='Макс. мощность, Вт')),
                ('body', models.CharField(default=None, max_length=50, verbose_name='Корпус')),
                ('ready', models.BooleanField(default=True, verbose_name='Открытый доступ')),
                ('maxcurrent', models.CharField(max_length=255, verbose_name='Максимальный ток коллектора , А')),
                ('maxvoltage', models.CharField(max_length=255, verbose_name='Максимальное напряжение коллектор-эмитер, В')),
                ('conditions', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.enviromentalcondition', verbose_name='Условия эксплуатации')),
                ('down', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.modeltxt', verbose_name='Файл модели')),
                ('technicaldescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.techologytask', verbose_name='Файл технического описания')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.type', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Название')),
                ('function', models.CharField(default=None, max_length=50, verbose_name='Производитель')),
                ('basicModel', models.CharField(default=None, max_length=50, verbose_name='Макс. мощность, Вт')),
                ('body', models.CharField(default=None, max_length=50, verbose_name='Корпус')),
                ('ready', models.BooleanField(default=True, verbose_name='Открытый доступ')),
                ('maxcurrent', models.CharField(max_length=255, verbose_name='Максимальный ток, А')),
                ('maxvoltage', models.CharField(max_length=255, verbose_name='Максимальное напряжение, В')),
                ('breakdownvoltage', models.CharField(max_length=255, verbose_name='Напряжение пробоя, В')),
                ('conditions', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.enviromentalcondition', verbose_name='Условия эксплуатации')),
                ('down', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.modeltxt', verbose_name='Файл модели')),
                ('technicaldescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.techologytask', verbose_name='Файл технического описания')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.type', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
