# Generated by Django 3.1.5 on 2021-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True, verbose_name='Имя заказчика')),
                ('email', models.EmailField(default=None, max_length=255, null=True, verbose_name='Электронный адрес')),
                ('phonenumber', models.CharField(default=None, max_length=25, null=True, verbose_name='Номер телефона')),
                ('description', models.TextField(default=None, null=True, verbose_name='Краткое описание')),
            ],
        ),
        migrations.AlterModelOptions(
            name='diod',
            options={'verbose_name': ('Диод',), 'verbose_name_plural': 'Диоды'},
        ),
        migrations.AlterModelOptions(
            name='transistorbp',
            options={'verbose_name': ('Биполярный транзистор',), 'verbose_name_plural': 'Биполярные транзисторы'},
        ),
        migrations.AlterModelOptions(
            name='transistorpolev',
            options={'verbose_name': ('Полевой транзистор',), 'verbose_name_plural': 'Полевые транзисторы'},
        ),
    ]
